### ISSUE TITLE
Protect Entities

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#1]
Some entities should be protected:

https://github.com/FAForever/api/search?utf8=%E2%9C%93&q=%40oauth.require_oauth

**Comment by micheljung** [comment]
It's not the entities that need to be protected, but the "routes" (which, except for achievements, aren't even implemented yet).

**Comment by IDragonfire** [comment]
My suggestion: We protect every entity in jsonapi:
with `@ReadPermission(any = {Role.NONE.class})`
Any active ReadPermission on class level

**Comment by micheljung** [comment]
So if we're talking about protecting entities (which is different from protecting routes with OAuth), I'm not yet sure whether to prefer an allow-all or deny-all approach for read permissions. Probably allow-all since there are only a few fields or entities that need protection. For write permissions, however, I'd definitely go deny-all and selectively allow writing.

**Comment by IDragonfire** [comment]
This is the current state ...
https://github.com/FAForever/faf-java-api/blob/develop/src/main/java/com/faforever/api/data/package-info.java
