### ISSUE TITLE
Link to steam

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#142]

**Comment by duk3luk3** [comment]
The "reference implementation" in the python api is here: https://github.com/FAForever/api/blob/develop/api/users_route.py#L366-L471

We've decided to explicitly require ownership of FA since it is required for the game, making no exceptions for people with "non-standard setups" (aka people who pirated the game, with a tiny amount of exceptions).

It has a small problem in the [steam response parsing](https://github.com/FAForever/api/blob/918893707b76374c3866c558aa1b54598aab5952/api/users_route.py#L445-L454) that I haven't gotten around to fix yet -

```python
    if steam_req.status_code == 200:
        try:
            steam_rep = steam_req.json()
            if steam_rep['response']['game_count'] > 0:
                for game in steam_rep['response']['games']:
                    if game['appid'] == FA_APPID:
                        found_game = True
                        break
        except:
logger.exception('Steam request parsing failed for steamid={}, user_id={}'.format(steamID, user_id))
```

`steam_rep['response']` is sometimes empty. This should be just a regular failure, equivalent to the response status code not being 200.

You can debug the steam api using curl:

`curl -s 'http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=STEAMAPIKEY&steamid=76561198390983227&format=json&appids_filter\[0\]=9420'`

You can get a STEAMAPIKEY for testing here: http://steamcommunity.com/dev/apikey
(We have a steam account for FAF with an API key to use in prod)

Please note that there's pretty heavy caching on the steam api, so changes you make to e.g. the public visibility of a profile you're testing against may not have an effect until several minutes later.

**Comment by Brutus5000** [comment]
Needs testing on a proper test server in combination with the website.
