### ISSUE TITLE
Login vs User vs Player

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#76]
Cleanup User Management in the api ...

Currently we have three classes
* `Login` general informations
* `User` contains only the password
* `Player` with additional game relevent informations (ladder, rating, clan)

**Comment by duk3luk3** [comment]
Important additional consideration:

* User names (or "display names" if implemented instead of allowing permanent login rename) must be restricted for 6 monts after last use to prevent name stealing

WIP implementation for python api is here: https://github.com/FAForever/api/pull/163

**Comment by micheljung** [comment]
@IDragonfire could you elaborate the `...` part? What should be cleaned up, and how would a clean version look like?

**Comment by IDragonfire** [comment]
Maybe a good first step is to have the same structure as in the java-server ....
The main problem is that some classes require `Player`, some requre `User`, some require Login and it is not easy to translate one object into the other ... Maybe have one `Player´ object with different components ....

**Comment by micheljung** [comment]
The structure *is* the same as in the java-server. I guess it boils down to the question whether users and players should be separated (one user can have multiple players or "characters", like Gyle) or not. Because right now both systems were built to support that, but since the underlying DB model does *not* support that, the `Login` abstraction got introduced which makes things a bit messy.

**Comment by Brutus5000** [comment]
Partially resolved in bddf85234f8dd65c7265bbdf7b54a4532b738a84
User contains the sensitive data with restricted access to the collection itself.
Player is open for everybody.
