### ISSUE TITLE
Add Entities for `UniqueId` UID Feature

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#88]
Add Entities for `UniqueId` UID Feature

**Comment by micheljung** [comment]
We are aware that this exposes how the UID check works (wasn't it disabled due to SteamLink anyway?) when we wanted to keep that closed source, are we?

**Comment by Brutus5000** [comment]
It's only visible to moderators.

**Comment by micheljung** [comment]
The source code is visible to everyone

**Comment by Sheikah45** [comment]
The fields are already explicitly stated in the schema spy of the database format or the source of the db migrations so I don't think this is divulging any new or more accessible info.

**Comment by micheljung** [comment]
True, yet the goal was to keep/make the inner workings private but this is going the opposite direction.

**Comment by Sheikah45** [comment]
The main issue as I see it is that at the moment this is of very little use to the people who would get the most utility out of it, the moderators, as they have no access to it since they do not have server access to actually view the database. The idea here is that for it to be of use they need to have some access to it which is why we set the permissions to be moderators only can view it. 
And if they moderators can't get to the information it isn't very helpful in the first place.
